language: java

# Skip "install" stage:
install: true

# Use container-based infrastructure:
sudo: false

dist: trusty
addons:
  apt:
    packages:
      - openjdk-6-jdk

# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'

env:
  - JDK=5
  - JDK=6
  - JDK=7
  - JDK=8
  - JDK=8
    ECJ=true
  - JDK=9
  - JDK=10
  - JDK=11
  - JDK=12
  - JDK=13
  - JDK=14-ea

script: ./.travis.sh
