jobs:
- job:
  strategy:
    matrix:
      JDK 5:
        JDK_VERSION: 5
  pool:
    vmImage: 'ubuntu-24.04'
  steps:
  - bash: |
      set -e
      url_var=JDK${JDK_VERSION}_URL
      JDK_URL=${!url_var}
      mkdir .jdk
      curl -L $JDK_URL -o .jdk/jdk.tar.gz
      tar -xzf .jdk/jdk.tar.gz -C .jdk --strip-components 1
      .jdk/bin/java -version
      echo "
      <toolchains>
        <toolchain>
          <type>jdk</type>
          <provides>
            <id>$JDK_VERSION</id>
            <version>$JDK_VERSION</version>
          </provides>
          <configuration>
            <jdkHome>$PWD/.jdk</jdkHome>
          </configuration>
        </toolchain>
      </toolchains>
      " > toolchains.xml
    displayName: Setup JDK
  - bash: |
      if [[ "$JDK_VERSION" -ge "17" ]]; then
        export JAVA_HOME=$PWD/.jdk
      else
        export JAVA_HOME=$JAVA_HOME_17_X64
      fi
      if [[ "$BUILD_SOURCEBRANCH" == "refs/heads/master" && "$JDK_VERSION" == "5" ]]; then
        ./mvnw -V -B -e --no-transfer-progress -f org.jacoco.build \
          verify -Djdk.version=$JDK_VERSION -Dbytecode.version=$JDK_VERSION \
          deploy:deploy -DdeployAtEnd \
          --toolchains=toolchains.xml --settings=.azure-pipelines/maven-settings.xml
      else
        ./mvnw -V -B -e --no-transfer-progress \
          verify -Djdk.version=$JDK_VERSION -Dbytecode.version=$JDK_VERSION -Decj=${ECJ:-} \
          --toolchains=toolchains.xml
      fi
    displayName: Build
    env:
      SONATYPE_USERNAME: $(SONATYPE_USERNAME)
      SONATYPE_PASSWORD: $(SONATYPE_PASSWORD)
